[package]
name = "todo_rust_server"
version = "0.1.0"
authors = ["Shelomanov Dmitry <userbq201@mail.ru>"]

[dependencies]
actix-web = "0.7.3"
serde = "1.0.70"
serde_derive = "1.0.70"
failure = "0.1.2"
dotenv = "0.13.0"
diesel = { version = "1.3.2", features = ["mysql"] }
env_logger = "0.5.12"
